  name: Unit tests

  on: [pull_request]
  jobs:
    tests:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - uses: actions/checkouts@v2
        - name: Use node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm install
          run: npm ci
        - name: tests
          run: npm test